version: '3'

services:
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: codejam
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "10455:5432"
